name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: dist/storybook
          build_command: yarn storybook:build
          checkout: false
